 @if($page->slug=='study-mdms-in-india')
            <table id="mdmsfee-andhrapradesh" width="100%">
                <thead width="100%">
                    <tr>
                        <th>Branch</th>
                        <th>CAT A ( Govt College)</th>
                        <th>CAT A ( Private College)</th>
                        <th>CAT B (MGMT Quota</th>
                        <th>NRI FEES</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Anaesthesiology</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Dermatology</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>General Medicine</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Paediatrics</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Psychiatry</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Emergency Medicine</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Respiratory Medicine</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Radiation Oncology</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Radiodiagnosis</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>ENT</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>General Surgery</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Obgy &amp; Gynae</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Opthalmology</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Orthopaedics</td>
                        <td>38,875</td>
                        <td>4,32,000</td>
                        <td>8,64,000</td>
                        <td>50,00,000</td>
                    </tr>
                    <tr>
                        <td>Pathology</td>
                        <td>38,875</td>
                        <td>1,35,000</td>
                        <td>2,70,000</td>
                        <td>15,00,000</td>
                    </tr>
                    <tr>
                        <td>Community Medicine</td>
                        <td>38,875</td>
                        <td>1,35,000</td>
                        <td>2,70,000</td>
                        <td>15,00,000</td>
                    </tr>
                    <tr>
                        <td>Microbiology</td>
                        <td>38,875</td>
                        <td>1,35,000</td>
                        <td>2,70,000</td>
                        <td>15,00,000</td>
                    </tr>
                    <tr>
                        <td>Forensic Medicine</td>
                        <td>38,875</td>
                        <td>1,35,000</td>
                        <td>2,70,000</td>
                        <td>15,00,000</td>
                    </tr>
                    <tr>
                        <td>Pharmacology</td>
                        <td>38,875</td>
                        <td>1,35,000</td>
                        <td>2,70,000</td>
                        <td>15,00,000</td>
                    </tr>
                    <tr>
                        <td>Biochemistry</td>
                        <td>38,875</td>
                        <td>61,200</td>
                        <td>1,22,400</td>
                        <td>8,00,000</td>
                    </tr>
                    <tr>
                        <td>Physiology</td>
                        <td>38,875</td>
                        <td>61,200</td>
                        <td>1,22,400</td>
                        <td>8,00,000</td>
                    </tr>
                    <tr>
                        <td>Anatomy</td>
                        <td>38,875</td>
                        <td>61,200</td>
                        <td>1,22,400</td>
                        <td>8,00,000</td>
                    </tr>
                </tbody>
            </table>
 @endif